# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: none

# Setup
title: "Tom's Things I Learned"
tagline: "Tom Fakes' Things I Learned"
description: "A blog to gather all the small things I encounter in software and life.<br>&nbsp;- Tom Fakes"
url: "https://tomfakes.com"

author:
  name:           'Tom Fakes'
  url:            https://tomfakes.com

paginate:         8

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/tomfakes/tomfakes.github.io
